### ISSUE TITLE
[FEAT] Add: API System

### ISSUE THREAD

**Issue by Jinlee057** [our-ml-flow/app#3]
## Background
- Request, Response 모두 리스트 타입으로 Streamlit과 통신합니다
- Request : 유저가 소유하고 있거나 관심있는 Collection을 List 형태로 요청받습니다
- Response : 주간 데이터기반으로 학습한 모델에 의해 계산된 추천 아이템 리턴합니다.

## Todo
- [ ] Pydantic 이용 Request, Response 모두 리스트 형식만 가능하게 데이터 유효성 검사
- [ ] Poetry 이용 의존성 관리
- [ ] 로컬개발 환경에서 테스트 진행
- [ ] 도커이용 컨테이너화
- [ ] 생성된 이미지 vm이식
